version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]

  - package-ecosystem: nuget
    directory: "/desktop/OpenDrop"
    schedule:
      interval: weekly
    labels: ["dependencies"]
